### ISSUE TITLE
Allow custom http client?

### ISSUE THREAD

**Issue by rahulpowar** [jimmysawczuk/recon#1]
Would be great to be able to specify a different client so a user could use a caching http model like https://github.com/gregjones/httpcache

https://github.com/jimmysawczuk/recon/blob/master/recon.go#L136 seems to be the point.

**Comment by jimmysawczuk** [comment]
Not a bad idea. If you want to open a PR feel free, otherwise I'll try to get to it somewhat soon.

**Comment by jimmysawczuk** [comment]
This is implemented as of #2.
